[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs",
  "storage-proofs/core",
  "storage-proofs/porep",
  "storage-proofs/post",
  "fil-proofs-tooling",
  "sha2raw"
]

[patch.crates-io]
# bellperson = { path = "../../../opensource/bellperson"}
bellperson = { git = "https://github.com/filecoin-project/bellman", branch = "fix-spawn-9" }
