[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs",
  "storage-proofs/core",
  "storage-proofs/porep",
  "storage-proofs/post",
  "fil-proofs-tooling",
  "sha2raw"
]

# waiting for release
[patch.crates-io]
neptune = { git = "https://github.com/filecoin-project/neptune", branch = "chore-bellperson-0-10-1" }
